### ISSUE TITLE
Day on timeline wrong?

### ISSUE THREAD

**Issue by coderDem** [iteratec/OpenSpeedMonitor#11]
Hello,

could it be that OSM get the wrong day for a date?
![timelinet](https://cloud.githubusercontent.com/assets/2386100/7184948/43444c4c-e460-11e4-9d20-db301ecd1607.PNG)
Is it possible to configure OSM to the right dates from Germany?

Best

**Comment by IteraSpeed** [comment]
Could you please check with HEAD. I can't reproduce this.

**Comment by nilskuhn** [comment]
Do you mean german date *format* in axis labels?

**Comment by sburnicki** [comment]
I can't reproduce this with the latest release. @coderDem: If you still experience problems, please feel free to reopen this issue.
