### ISSUE TITLE
No Piking in diagram anymore

### ISSUE THREAD

**Issue by mirkoebert** [iteratec/OpenSpeedMonitor#14]
On longer work with OSM, the picking of a value doesn't work anymore. A page reload doesn't help. 

MacOSX 10.11.3
Safari 9.0.3 

The console contains a lot of CSS warnings.

**Comment by nilskuhn** [comment]
Sorry, I can't reproduce that. Don't have a MAC. Could you please check again in actual version.
For example [here](http://demo.openspeedmonitor.org/eventResultDashboard/showAll?selectedInterval=-1&selectedTimeFrameInterval=259200&from=11.10.2016&fromHour=9%3A50&to=14.10.2016&toHour=9%3A50&selectedFolder=30&selectedFolder=27&selectedFolder=26&selectedFolder=24&selectedFolder=28&selectedPages=20&_selectedAllMeasuredEvents=&selectedAllMeasuredEvents=on&_selectedAllBrowsers=&selectedAllBrowsers=on&_selectedAllLocations=&selectedAllLocations=on&_selectedAllConnectivityProfiles=&selectedAllConnectivityProfiles=on&_includeNativeConnectivity=&_includeCustomConnectivity=&selectedAggrGroupValuesUnCached=docCompleteTimeInMillisecsUncached&trimBelowLoadTimes=&trimAboveLoadTimes=&trimBelowRequestCounts=&trimAboveRequestCounts=&trimBelowRequestSizes=&trimAboveRequestSizes=&_action_showAll=Show&selectedChartType=0)?

**Comment by sburnicki** [comment]
@mirkoebert: Can you try to reproduce this issue with the latest version? If you still have trouble, feel free to reopen this issue :)
