### ISSUE TITLE
OSM - Customer Journeys

### ISSUE THREAD

**Issue by MaxSchoenke** [iteratec/OpenSpeedMonitor#15]
@nilskuhn  @IteraSpeed 

Dear Mr. Kuhn,

as requested, I’m repeating my questions in this forum.

We are monitoring some sites with the OSM at the moment. We are very happy to have such a practical tool. But still it left us with some questions:

1)	OSM provides the possibility to follow customer journeys through a multistep WPT session. For example it follows the user through his experience from the entry page, through the search page finishing at any product page. The product page in this case is named „customer journey“ by many of your demo-scripts. But as far as I understand the OSM, this site is also measured like a single page. This means that we can see the benefits of the site being faster as some parts of it are cached, but not that OSM gives you the complete journey results.

Does OSM therefore provide a possibility to measure the output time of a complete customer journey? Or is that only possible by manually summing up all the single page measurements?

2)	The start or entry page is always viewed with an empty cache, so wpt provides us with a first view of this site. (unless the customer journey starts at a different site navigation to the start site)

How is that affecting an optimisation strategy? 
If all js/ css and other files are loaded on the first page all the pages coming after that would be super quick to load because the cache is pretty full. But in reality isn’t it more likely to optimise every page by itself? 
So does OSM somehow have the possibility to show the start page with a cached state not being the same as RV but closer to reality (like a partly cached state e.g. if the user was on this site the day before…?)

3)	The CSI is always connected to a single site. Is there any planning in developing the OSM so it can also measure the CSI over a customer journey?

Thank you for your reply!

M. Schoenke

**Comment by nilskuhn** [comment]
1)

First to clarify:

OSM provides the possibility to write scripts in [WebPagetests scripting DSL](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting) with multiple steps. So you can configure whole customer journeys a user takes through your application. To _measure_ these journeys and provide one result for every single step within this journey you will need to use a webpagetest server and agent capable of multistep measurements. [Official version](http://www.webpagetest.org/) of WebPagetest isn't capable of multistep functionality at the moment. So you will need to host your own wpt agents and -server based on [this fork](https://github.com/iteratec-hh/webpagetest).

Your question:

That we named some of the steps with _customer_journey_ suffix isn't important. That was just to distinguish between the measured steps of the same page type measured in a single or multistep measurement. It doesn't mean that the whole journey is measured completely.

See the following two scripts as an example.

Measuring product page as _amazon\_product\_DouglasAdams\_customer\_journey_ within a journey:

    setEventName    Amazon_homepage
    navigate    http://www.amazon.de
    setEventName    Amazon_search_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/s/ref=nb_sb_noss_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Douglas%20adams
    setEventName    amazon_product_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/Per-Anhalter-durch-die-Galaxis/dp/3453146972/ref=sr_1_1?ie=UTF8&qid=1415398775&sr=8-1&keywords=Douglas+adams

Measuring product page as _amazon\_product\_DouglasAdams_ in single step test:

    setEventName    amazon_product_DouglasAdams
    navigate    http://www.amazon.de/Per-Anhalter-durch-die-Galaxis/dp/3453146972/ref=sr_1_1?ie=UTF8&qid=1415398775&sr=8-1&keywords=Douglas+adams

If you would like to measure the timings for a complete journey you can use [WebPagetests combineSteps-Command](https://sites.google.com/a/webpagetest.org/docs/using-webpagetest/scripting#TOC-combineSteps). I never tried that with OSM and can not hardly find a reason to do so. You will have more fuzziness in your results the more steps your journey contains. To get a detailed view of the performance of your application you should explore your single page types separated to minimize fuzziness, I think. But if you really need the timings of a whole journey you can give _combineSteps_ a try.

2)

We have to distinguish between your homepage and an entry page. By entry page we mean the first page in the user session. For the most web applications the homepage is the entry page in most of the sessions / customer journeys. But the entry page can be another page than the homepage for large shares, too.

To answer your question:

Yes, you should optimize every page by itself. But you should derive information about the page types which get visited as entry pages in your application from logging data first. With the information about which page types are your entry pages and at what share in hands, you can adapt your OSM scripts correspondingly. If you know 65% of your homepage calls are entry pages and 15% of your product pages are, for example, you could use the following two scripts:

Homepage as entry page, product page as follow up.

    setEventName    Amazon_homepage
    navigate    http://www.amazon.de
    setEventName    Amazon_search_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/s/ref=nb_sb_noss_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Douglas%20adams
    setEventName    amazon_product_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/Per-Anhalter-durch-die-Galaxis/dp/3453146972/ref=sr_1_1?ie=UTF8&qid=1415398775&sr=8-1&keywords=Douglas+adams

Product page as entry page, homepage as follow up:

    setEventName    amazon_product_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/Per-Anhalter-durch-die-Galaxis/dp/3453146972/ref=sr_1_1?ie=UTF8&qid=1415398775&sr=8-1&keywords=Douglas+adams
    setEventName    Amazon_search_DouglasAdams_customer_journey
    navigate    http://www.amazon.de/s/ref=nb_sb_noss_1?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&url=search-alias%3Daps&field-keywords=Douglas%20adams
    setEventName    Amazon_homepage
    navigate    http://www.amazon.de

To take the percentages into consideration you could create the following Pages in OSM and weight them respectively:

- Homepage_entry: weight=65
- Homepage_follow: weight=35
- Product-page_entry: weight=15
- Product-page_follow: weight=85

[Here](http://demo.openspeedmonitor.org/csiDashboard/weights) you can see page weights for CSI in demo instance (click on button _Weights CSI_).

3)

The Customer satisfaction index (CSI) is a method to aggregate all the synthetic performance measurements you do to one single index. So it already combines all the page type measurements of all your relevant customer journeys to a single index if you use the right scripts.

An example:

We measured some pages of three large java conferences for several days. [Here](http://demo.openspeedmonitor.org/csiDashboard/showAll?aggrGroup=daily_page&selectedTimeFrameInterval=0&_setFromHour=&from=02.02.2016&fromHour=0%3A00&_setToHour=&to=05.02.2016&toHour=23%3A59&_includeInterval=&selectedFolder=22&selectedFolder=21&selectedFolder=20&selectedPages=11&selectedPages=10&_selectedAllMeasuredEvents=&selectedAllMeasuredEvents=on&_selectedAllBrowsers=&selectedAllBrowsers=on&_selectedAllLocations=&selectedAllLocations=on&_action_showAll=Show) you see the csi aggregated for two of the measured page types. If you klick on a data point you come to all the single measurements with different browsers. The CSI's of the measured pages get aggregated (weighted respective the page weights you configure) to one CSI per application. [Here](http://demo.openspeedmonitor.org/csiDashboard/showAll?aggrGroup=daily_shop&selectedTimeFrameInterval=0&_setFromHour=&from=02.02.2016&fromHour=0%3A00&_setToHour=&to=05.02.2016&toHour=23%3A59&_includeInterval=&selectedFolder=22&selectedFolder=21&selectedFolder=20&selectedPages=11&selectedPages=10&_selectedAllMeasuredEvents=&selectedAllMeasuredEvents=on&_selectedAllBrowsers=&selectedAllBrowsers=on&_selectedAllLocations=&selectedAllLocations=on&_action_showAll=Show) you can see these CSI graphs over the same period of time.

Furthermore we don't plan to calculate a CSI for customer journeys.

I hope that answers your question.
