### ISSUE TITLE
Can't set Max Download Time value in OSM Configuration

### ISSUE THREAD

**Issue by moumou124** [iteratec/OpenSpeedMonitor#165]
Hello, 

I used the last develop version with docker, everything work but when I want to change the Max Download Time value in OSM Configuration panel, the default value(60 minutes) is always used, whatever value I set in the OSM Configuration panel. I can see my changes in the panel, but it has no impact on the Max Download Time which still stays at 60 minutes. Is it normal? 

Thanks a lot !

**Comment by finnmartens** [comment]
Hi,
I have been able to reconstruct the problem and find out what caused it. The settings in the OSM Configuration window were indeed set correctly. However, the maximum download time of a job was not saved correctly according to this setting, but was instead set to 60 minutes by default. I am currently working on this problem and a fix should be available soon. Thank you for opening an issue!

Also note that this default value only works for newly created jobs and does not update the maximum download time of an existing job.

Best Regards!

**Comment by finnmartens** [comment]
I'm sorry that the topic has been somewhat missed, I do hope you've already noticed that the bugfix has been merged for some time. The issue has been addressed in [PR 168](https://github.com/iteratec/OpenSpeedMonitor/pull/168).
I'm therefore closing this issue now. Better late than never.

Best regards!
