### ISSUE TITLE
job activation error

### ISSUE THREAD

**Issue by csiebert** [iteratec/OpenSpeedMonitor#18]
Hi,

after updating to 3.4.8 some jobs can not be activated (others can).

Do i have to fix something manually?

![osm_activation_error](https://cloud.githubusercontent.com/assets/367330/13820674/a7d114a6-eb9e-11e5-8645-fc7c952f0ad9.JPG)

**Comment by nilskuhn** [comment]
OK, you found a bug we unfortunately introduced with commit beff860433398fb488ee1c631ad71637a7670b06. We will fix this asap. 

If you don't want to wait (should not take too long) you can take the last commit before (8c14b6df74675d7de54eea93fff7b6f53d45c3ec). What we (tried to) introduce is that subsequent tasks after saving of a new wpt results (like csi aggregation and reporting to graphite servers) can't rollback database transaction that saves wpt results in OpenSpeedMonitor.

Sorry for your inconveniences.

**Comment by csiebert** [comment]
Thanks, it works when using the commit before.

**Comment by nilskuhn** [comment]
This is fixed in latest version.
