### ISSUE TITLE
Unable to define WPT Server access key?

### ISSUE THREAD

**Issue by spuzon** [iteratec/OpenSpeedMonitor#20]
I didn't find that so created issue.

My WPT Server API is protected with access key, where can I define it in OSM?

OSM reports this message from WPT server when i try to fire job: Error: An error occurred processing your request (missing API key)

**Comment by nilskuhn** [comment]
Yes, you're rigtht. That's still missing :(
We will add support for providing API Keys for configured WebPagetest servers asap.

**Comment by iteratec-hh** [comment]
You can pull the HEAD from master branch. 
Than you can add your apiKey via edit view of WebPageTestServer in OSM gui.
