### ISSUE TITLE
Missing aggregation of custom performance marks

### ISSUE THREAD

**Issue by moehlone** [iteratec/OpenSpeedMonitor#21]
If I set custom marks with the native performance interface in javascript (window.performance.mark), the measured timings appear within the table of the details page. Unfortunately I found no way to get this data in an aggregated format like CSV.

It would be very helpful to evaluate measurings in different render paths.

Tanks in advance,
Philipp

**Comment by nilskuhn** [comment]
Would be a useful feature. Not just csv export, also to have custom timings as time series in dashboard.
We wil mplement that soon.

**Comment by nilskuhn** [comment]
We implemented full support for usertimings with [version 4.4](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v4.4.0).
