### ISSUE TITLE
External configuration file - production environnent

### ISSUE THREAD

**Issue by moumou1247** [iteratec/OpenSpeedMonitor#22]
Hello, 

I got an issue regarding the production deployment : 

I used the OpenSpeedMonitor-config.yml with my infos about the intial admin and root user and also the datasource infos with all the data linked to my MySQL database hosted locally, I moved this file in this path home/user-directory/.grails/OpenSpeedMonitor-config.yml but when I deploy the web app it seems like those config are not used because I can’t access the login interface with the credentials I added in the config file and my MySQL database doesn’t shows any signs of openspeedmonitor tables. I also use “./gradlew assemble” to produce my war file for prod environment. 
 
(I joined the pattern of the external config file I used)
 
[pattern.txt](https://github.com/iteratec/OpenSpeedMonitor/files/644605/pattern.txt)

Do I need to specify this path in a groovy configuration file ? 
 
Thanks !

**Comment by nilskuhn** [comment]
There are three places OpenSpeedMonitor (osm) looks for external configuration file at startup:

1) If an env variable `osm_config_location` is set than this conf file will be taken. So if you start the servlet container you deploy the osm in with a jvm arg `-Dosm_config_location=/path/to/your/OpenSpeedMonitor-config.yml` than the conf file at this place will be used.    
2) You may locate the osm config file somewhere in the classpath of the war file.
3) The possibility you mentioned yourself. Save your osm conf file at `/home/<user-that-starts-the-container>/.grails/OpenSpeedMonitor-config.yml`. This file of course must be readable for the owner of the servlet container process and the name of the file must exactly be `OpenSpeedMonitor-config.yml`.

These three possibilities get used in the order I listed them here. So path in env variable would overwrite classpath and user folder of container user.

**Comment by sburnicki** [comment]
@moumou1247: Are you still having trouble with this issue? If yes, feel free to reopen the issue :)
