### ISSUE TITLE
Show Rest Call (URL) for result timeline graphics data

### ISSUE THREAD

**Issue by mirkoebert** [iteratec/OpenSpeedMonitor#24]
If I have result timeline graphics then I need links to get these data via REST call (complete URL). Data means the the where the graphics is generated from not the XY_ponits of the figure self.

**Comment by j0weiss** [comment]
We have a REST endpoint to get the desired data, see [Swagger definition](https://demo.openspeedmonitor.org/webjars/swagger-ui/3.17.0/index.html?url=/rest/man).

Also we are currently working on migrating the time series chart into an Angular page and rebuild the chart itself with pure d3.js. This means a REST endpoint will be exposed for the selected data.
Another way to get the data is to use the CSV export feature on the result list.

I hope this helps.
