### ISSUE TITLE
Cannot delete scripts

### ISSUE THREAD

**Issue by minddazed** [iteratec/OpenSpeedMonitor#28]
Even when I'm logged in as root or admin I'm unable to delete some scripts. I get the error "Script xxxx could not be deleted." I would think a super user can delete everything.

**Comment by MoWeg** [comment]
Currently even a super user cannot delete scripts that are used within a job.  To delete this particular script, you need to remove it from jobs or delete the jobs in which the script is used.
We are working on an improvement.

**Comment by minddazed** [comment]
These particular scripts are not used in any job, but I am still unable to delete. Any ideas?

**Comment by MoWeg** [comment]
We will have a look into it. To address this issue, it would be helpful if you provide further information. 

Which version of the OpenSpeedMonitor you are using?
Do you have any logs or stacktraces describing this issue that you are able to share?

**Comment by jpvincent** [comment]
Hi

I have a similar problem, but with more details.

I have been able to remove one of my old script, after de-attaching it from the job, however I have one last script that still resists. Here is the error I have :
Script HP desktop - no cookie could not be deleted due to at least one depending ArchivedScript

How do we manage the "ArchivedScript" ?

**Comment by nilskuhn** [comment]
We have a history of wpt script versions implemented. Whenever you edit and save an existing script a new ArchivedScript is created. The old versions you can view and restore via  `Version control` button in `script/edit` view.

Obviously scripts with a history can't be deleted. We didn't really have the need for deleting old scripts so far. 

We will have a look for the possibility to delete scripts without a Job reference, but a history.

**Comment by j0weiss** [comment]
I'm closing this issue as the comment of @nilskuhn points to a workaround to delete scripts.
Feel free to open it again if this is still a usecase for you.
