### ISSUE TITLE
CSI Benchmark does not recognize job group

### ISSUE THREAD

**Issue by carloscohen2202** [iteratec/OpenSpeedMonitor#289]
Hi,

I'd like to report a bug on version 5.3.2 
I'm trying to run a CSI benchmark but it shows me an error (see screenshot). I've selected more than one Job Group but the OSM still says me that I have to select one.

![image](https://user-images.githubusercontent.com/40352988/68116739-d4167a00-fefb-11e9-8893-8cbf2fe44b2e.png)

Thank you very much for the correction of this issue.

**Comment by j0weiss** [comment]
Thanks for reporting this issue. We fixed it with the referenced pull requests.

When the review of the pull request was successful we try to create a new release containing this bugfix as soon as possible.

**Comment by j0weiss** [comment]
Fixes released with [v5.3.3](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v5.3.3)
