### ISSUE TITLE
Server error while trying page comparison

### ISSUE THREAD

**Issue by carloscohen2202** [iteratec/OpenSpeedMonitor#290]
Hi,
I'd like to report a bug on version 5.3.2
While trying the page comparison function, I get an internal server error after selecting the job groups, page and clicking at show.  

![image](https://user-images.githubusercontent.com/40352988/68119046-ea273900-ff01-11e9-88c4-886bc838db95.png)

Thank you very much in advance for the correction of this issue.

**Comment by j0weiss** [comment]
Thanks for reporting this issue. We fixed it with the referenced pull requests.

When the review of the pull request was successful we try to create a new release containing this bugfix as soon as possible.

**Comment by j0weiss** [comment]
Fixes released with [v5.3.3](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v5.3.3)
