### ISSUE TITLE
Metric selection not possible without data

### ISSUE THREAD

**Issue by BennyLi** [iteratec/OpenSpeedMonitor#299]
Previously, the metrics in the performance aspect configuration were only made available for selection when a data point was selected in the graph. But if no data is available, you cannot select data points and you never get to the metric selection. So without data, you cannot select metrics.

**Comment by DanielSteger** [comment]
Comment out `this.metricFinderService.loadData(from, now, appId, pageId, browserId);` in `edit-aspect-metrics.component.ts` to reproduce the configuration without event result data.
