### ISSUE TITLE
Query parameters (URL containing ampersands) get cut off when used in scripts

### ISSUE THREAD

**Issue by DominiqueFuchs** [iteratec/OpenSpeedMonitor#31]
When using a simple script in OpenSpeedMonitor (tried different versions 4.4.0 and 4.3.X) like this:

`setEventName   Test`
`navigate   http://www.test.org/nowQuery?base=123456andOne&andTwo&andThree`

and running a corresponding job the webpagetest instance only receives the part until the first ampersand (query parameter) (in this example http://www.test.org/nowQuery?base=123456andOne). You can see that question mark and equal sign seem to be interpreted/parsed correctly, but ampersands break the URL transmission.

When looking at the POST log on the server (webpagetest on nginx/debian, OSM running on tomcat8, accessible upstream via proxy_pass) the URL is not encoded but complete. Trying to full encode the URL in the OSM script results in double encoding (automatically encoding the percent sign used to encode by hand in the script), so this seems not to be the intentioned way. Unfortunately I cannot find any documentation about the way OSM handles this. 

Several weeks ago I already posted this issue at the WPT project, thinking this could be an issue by WPT interpreting the POST. Unfortunaly this seemed to be the wrong place. However the issue still persists here and I just can't figure out how to fix this. For more infos see the relating issue:

[Webpagetest Issue 975](https://github.com/WPO-Foundation/webpagetest/issues/975)

Any clues on this? Thanks in advance!

**Comment by j0weiss** [comment]
Hi,
I was able to reproduce the faulty behaviour and I think you're right with the assumption, that there is an issue with wrong or not existing URL encoding.
We're going to have a deeper look into that and will come back to you.

**Comment by j0weiss** [comment]
We found the problem and fixed it in a623a0c214ea7da3cae2fd1eca62d9b78ddad28b on the develop branch. With the next release it will be on the master.
Thanks for your input!

**Comment by j0weiss** [comment]
FYI: We solved the issue with release [4.5.0](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v4.5.0)
