### ISSUE TITLE
Use the job ID instead of the name when retrieving the WPT results

### ISSUE THREAD

**Issue by BennyLi** [iteratec/OpenSpeedMonitor#312]
Currently, we read the label from the result XML coming from the WPT server to assign the measurement job that triggered the result to the result.

This is error-prone and the WPT server does not allow a number of special characters in the label and simply cuts them away. This has already caused results not to be persisted in the OSM on several occasions if we have used special characters in the job name.

We should transfer the ID of the triggering measurement job from the `JobRunService` (formerly JobProcessingService) via the `WptInstructionService` (formerly ProxyService) to the `JobResultPersisterService` (formerly ResultPersisterService). This would eliminate the need for the label from the result-xml to determine to which measurement job the result belongs.

**Comment by DanielSteger** [comment]
Already done in commit [c8bc22d](https://github.com/iteratec/OpenSpeedMonitor/commit/c8bc22d8d6ea91ba8ebcfdd11a64515e6853cd26) and [a14217e](https://github.com/iteratec/OpenSpeedMonitor/commit/a14217e928b9148940f69c1ef03d2c485a9cd615)?
