### ISSUE TITLE
Provide the "Capture Dev Tools Timeline" option

### ISSUE THREAD

**Issue by jpvincent** [iteratec/OpenSpeedMonitor#32]
Hello !
When programming a job involving Chrome, I'd like it to be able to record the dev tools timeline, as in the WPT UI => advanced settings => chrome tab.

We could add that into the advanced options, as this is chrome-only and it adds up to the test overhead and fills up the disk a bit faster.

I need it because I'm monitoring the CPU times of the 3rd parties, here is my workflow : 
- tests are planned thanks to OSM
- a script of mine get the latest WPT tests (thank you very much for the REST API !)
- it would extract the timeline from the WPT server, thanks to https://github.com/marcelduran/webpagetest-api
- the timeline is analyzed with https://github.com/jpvincent/3rd-party-cpu-abuser
- results are sent in a dashboard of mine

I currently can't use OSM to program tests with dev tools timeline turned ON.

Thanks in advance

**Comment by nilskuhn** [comment]
Hi, 

I'm not quite shure whether I got your point. In the latest OSM version (4.4) we have the WPT option to persist Chrome's devtool timeline integrated:
![osm_option_devtools](https://user-images.githubusercontent.com/1001134/34721313-988348e8-f542-11e7-8f3b-d85d7c337fc4.png)

Did you miss that one or isn't it working as expected?

Your timeline analyzer looks interesting, btw. Would be nice to have CPU times in OSM dashboards.

Regards, Nils

**Comment by jpvincent** [comment]
Oh, it's me not spotting this tab in one of my installation (currently off), but I can see it appear on another one.
Does it appear dynamically by looking at the Location field ?

**Comment by jpvincent** [comment]
and thanks for the interest in the CPU times : I really think webperf is moving slowly from a network contention problem to a CPU contention problem on most devices, so yeah a graphe on that would be interesting :)

**Comment by nilskuhn** [comment]
The tab should always be visible in OSM.

BTW: We have some problems viewing recorded devtools timeline in wpt when runnig the server in a docker container. Seems  that a redirect header is added to the page too late, so the browser won't follow it anymore. We fix that one and will create a PR for that.

**Comment by jpvincent** [comment]
Now my dev OSM is back, I can confirm that the "chrome" tab does not appear : 
![image](https://user-images.githubusercontent.com/427625/34764657-6e461f8a-f5ef-11e7-83e3-f30e411b8df3.png)

It appears though on my production OSM : what could cause this ?

> BTW: We have some problems viewing recorded devtools timeline
I have the same problem but did not investigate yet, thank you for PR

**Comment by j0weiss** [comment]
We introduced many of the advanced settings for Chrome in version [v4.3.0](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v4.3.0) but I assume you are running a version later than that.

I looked into the code and we check if the _Location_ option selected in the _Job Settings_ tab contains the string `'Chrome'`. If this is not the case we hide the _Chrome_ tab. So my guess would be that your label of the selected location doesn't match that criteria, though it is a Chrome browser.

Maybe we need to think again about that "feature".

**Comment by jpvincent** [comment]
my location name is `Local_Seven:chrome`
I guess the lowercase is at play here

**Comment by j0weiss** [comment]
You're right.
I opened a ticket for us to discuss how we want to solve this. Either we think it is a valid feature, but then the logic to test if it is a Chrome browser must be enhanced or we skip this at all and always show the Chrome tab.
But the quick fix for you would be to rename your browser in the WPT settings to `Chrome`. I hope this works for you.

**Comment by jpvincent** [comment]
Thank you

**Comment by j0weiss** [comment]
With release [4.5.0](https://github.com/iteratec/OpenSpeedMonitor/releases/tag/v4.5.0) we fixed this issue by displaying the Chrome tab no matter which browser is used. We think that this is an advanced feature which is used by users who know their way around in OSM. So, we think that there will be no confusion when displaying a tab for Chrome only features, even though the browser for this job is not Chrome.
