### ISSUE TITLE
Postgresql support?

### ISSUE THREAD

**Issue by 007lva** [iteratec/OpenSpeedMonitor#331]
Hello guys and thanks for open source this awesome project. I work mostly with Postgresql and would like to know if OpenSpeedMonitor can be deployed with it instead of MySQL.

**Comment by nilskuhn** [comment]
Sorry, but officially we only support MySQL.

We tested Postgres some time ago, but although we are using Liquibase and Hibernate which should abstract from concrete RDBMS some of the [change sets](https://github.com/iteratec/OpenSpeedMonitor/tree/develop/grails-app/migrations) which create the schema on start up didn't work. So shouldn't be too much work to get this running, but I won't expect it to work out of the box.

**Comment by 007lva** [comment]
Thanks!
