### ISSUE TITLE
Trying to understand the Event / page distinction

### ISSUE THREAD

**Issue by jpvincent** [iteratec/OpenSpeedMonitor#35]
Hi
We are trying to understand how to name correctly the pages and the events in the scripts.
Let's take this script :
```
setEventName HP:::no-cookie
navigate https://example.com
```
In the script UI, it says that "The following new pages will be created: HP" and " The following new measuredEvents will be created: no-cookie (HP)"

In the API it gives : 
```json
		"page": "HP",
		"step": "no-cookie",
```

Everything is coherent and we get that the first part of the event name is the page, the second part is a "step". We use the step to qualify the condition of the test (with or without ads, cookies and so on), so when we wanted to navigate to a second page, we added
```
setEventName HP:::no-cookie
navigate https://example.com
setEventName FillSearchBar:::no-cookie
navigate https://example.com/page2
```
We now have an error stating that "each measuredEvent must only be used once"
<img width="377" alt="image" src="https://user-images.githubusercontent.com/427625/37347492-409db962-26d2-11e8-994b-2e4f60acb47e.png">

From our point of view, we change of page (first part) but the condition of navigation (second part) remains the same (no-cookie) but we are not allowed to do it this way.
The possible workaround is to invert the step and the page
```
setEventName no-cookie:::HP
navigate https://example.com
setEventName no-cookie:::FillSearchBar
navigate https://example.com/page2
```
But of course 'no-cookie' in this case would be considered as the page name and it will lead to misunderstandings. Moreover we have weird "undefined" appearing in the UI
<img width="622" alt="image" src="https://user-images.githubusercontent.com/427625/37348859-6899929e-26d5-11e8-9676-91da9a5e8b4c.png">

I have 3 questions :
* Can you explain how the page/step with the `:::` is supposed to be used ? It does not appear in the [documentation](https://github.com/iteratec/OpenSpeedMonitor/blob/master/README.md#set-up-measurements)
* An alternative for us would be to forget about the step and use the script or job names as our test's condition, but this information does not appear in the API : could you provide it ?
* How would you do to separate tests for the same page but with different conditions (device, network condition, logged in or not …) : the job group names ?

Thanks in advance

**Comment by nilskuhn** [comment]
You are right, the `:::` delimits the page from the measured event. We understand the page more like a page _type_. We typically share that page type between different applications we measure within different JobGroups in a single OpenSpeedMonitor instance. 

For example:

    Homepage:::HP_Amazon
    Homepage:::HP_Taobao
    Homepage:::HP_Ebay

To measure the same page in different states is another use case we typically have. For example you could measure the basket of an online shop with different number of articles inside:

    Basket:::Basket_empty
    Basket:::Basket_1_Item
    Basket:::Basket_5_Items
    Basket:::Basket_15_Items

The single results of your OpenSpeedMonitor jobs contain the following informations about the measurement they are based on:

* `JobGroup` Typically used for different applications.
* `Page` The page type.
* `MeasuredEvent` The event (aka step) within the measured customer journey.
* `Location` The WebPagetest location of the result.
* `Browser` The browser/device the result was measured on.

These attriutes may be used to filter results in the [OpenSpeedMonitor API](https://demo.openspeedmonitor.org/rest/man), e.g. in the `resultsbetween` function. Each result provided by the api function contains these informations.

In your case defining measured events for the same pages but with different conditions, I would suggest to add these sort of informations to the measured event: 

    //default
    setEventName HP:::HP
    navigate https://example.com
    setEventName Search:::FillSearchBar
    navigate https://example.com/page2
    
    //without cookie
    setEventName HP:::HP_no-cookie
    navigate https://example.com
    setEventName Search:::FillSearchBar_no-cookie
    navigate https://example.com/page2

    //without ads 
    setEventName HP:::HP_no-ads
    navigate https://example.com
    setEventName Search:::FillSearchBar_no-ads
    navigate https://example.com/page2

So you can use the page types `HP` or `Search` to aggregate all manifestations of the page types in the different OpenSpeedMonitor dashboards. In addition it's still possible to differentiate the different variants.

We are not really happy with that tricky differentiation by `:::` delimiter but at the moment it's the best way to put special attributes of the measured steps into the `MeasuredEvent` of it.

**Comment by jpvincent** [comment]
Thank you so much for taking the time to answer.

We'll apply your suggestion, it works for our use case, and there is no need to add more things in the API eventually.

Cheers
