### ISSUE TITLE
Script UI falsely reports an event is not followed by page view cmd 

### ISSUE THREAD

**Issue by cegue** [iteratec/OpenSpeedMonitor#36]
*Steps to reproduce:*
1. Go to OpenSpeedMonitor scripts UI
2. Enter:
```
setEventName foo
navigate some_url
<any non-page-view cmds like setValue, sleep, etc>
setEventName bar
navigate some_other_url
```
3. UI fails to allow creation of script due "This setEventName statement has no effect as it is not followed by a page view command."

*Expected behavior:*
OpenSpeedMonitor scripts UI allows creation if the setEventName is followed by a page view command such as navigate.

*Workaround:*
Add a navigate cmd before the setEventName

I guess, probably wrong, that this workaround will generate inaccurate reports as many objects will be effectively cached by the browser before the second navigate included in the page report (setEventName bar in the example above).

**Comment by cegue** [comment]
Pfff I had the wrong script. Feel free to close this ticket. Sorry about the noise.

**Comment by nilskuhn** [comment]
No problem.
