### ISSUE TITLE
Status of this project ?

### ISSUE THREAD

**Issue by jpvincent** [iteratec/OpenSpeedMonitor#370]
Hi !

I noticed a few things :
* https://demo.openspeedmonitor.org/ does not answer at all
* no PR from an human since 29 Jun 2020 (https://github.com/iteratec/OpenSpeedMonitor/pull/354) 
* since the buy from Catchpoint, WebPagetest has change its licence

Is this project deprecated ? If so, that would be nice to indicate it on the website and in the README file, thanks in advance !

**Comment by sburnicki** [comment]
Hey @jpvincent,
thanks for opening this issue. You are absolutely right, we stopped working on this project some time ago and missed to communicate this correctly.
We have just written appropriate notes on the website and in the README.

**Comment by jpvincent** [comment]
thank you for the clarification !
